### ISSUE TITLE
warning: use location instead

### ISSUE THREAD

**Issue by jeffijoe** [pulumi/pulumi-gcp#153]
When doing `new gcp.container.Cluster(name, { region: 'us-east1' })`, the following warning presents itself:

```
verification warning: "region": [DEPRECATED] Use location instead
```

When I switch to use `location` with the same value:

```
error: Plan apply failed: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
```

**Comment by stack72** [comment]
Hi @jeffijoe 	

Firstly, please accept my apologies for the late response to this issue. This is something we are continually trying to get better at. 

Secondly, I have not been able to recreate this issue. I am using the following code:

```
import * as gcp from "@pulumi/gcp";

const primary = new gcp.container.Cluster("primary", {
    initialNodeCount: 1,
    location: "us-central1",
    // We can't create a cluster with no node pool defined, but we want to only use
    // separately managed node pools. So we create the smallest possible default
    // node pool and immediately delete it.
    removeDefaultNodePool: true,
});
```

When I run the command `pulumi up --yes`, I get the following output:

```
╰$ pulumi up --yes
Previewing update (dev):

     Type                      Name            Plan
 +   pulumi:pulumi:Stack       gcp-gh-153-dev  create
 +   └─ gcp:container:Cluster  primary         create

Resources:
    + 2 to create

Updating (dev):

     Type                      Name            Status
 +   pulumi:pulumi:Stack       gcp-gh-153-dev  created
 +   └─ gcp:container:Cluster  primary         created

Resources:
    + 2 created

Duration: 6m3s
```

Can you possibly tell me if this is still an error you are getting?

Thanks

Paul

**Comment by jeffijoe** [comment]
These are the options I am using:

```ts
  const kubeVersion = "1.13.6-gke.13";

  // Default values for constructing the `Cluster` object.
  const defaultClusterOptions = {
    nodeCount: 1,
    nodeMachineType: "n1-standard-1",
    minMasterVersion: kubeVersion,
    masterUsername: "",
    masterPassword: ""
  };

  const cluster = new gcp.container.Cluster(`${name}-${region}`, {
    project,
    location: "us-east1",
    initialNodeCount: config.nodeCount || defaultClusterOptions.nodeCount,
    minMasterVersion: defaultClusterOptions.minMasterVersion,
    removeDefaultNodePool: true,
    network: network.name,
    subnetwork: subnet.name,
    masterAuth: {
      username: defaultClusterOptions.masterUsername,
      password: defaultClusterOptions.masterPassword
    }
  });
```

This generates:

> Plan apply failed: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.

**Comment by stack72** [comment]
Hi @jeffijoe 	

Please can you tell me what versions of pulumi and pulumi-gcp that you are on?

Paul

**Comment by jeffijoe** [comment]
Hey @stack72 , I'm on Pulumi 0.17.25 (latest brew) and

```
"@pulumi/gcp": "^0.18.5",
"@pulumi/kubernetes": "^0.23.1",
"@pulumi/pulumi": "latest",
```

Upgrading those to latest causes a full-on failure of

```
    Error: Unexpected struct type.
        at Function.proto.google.protobuf.Value.fromJavaScript (/Users/jeff/Projects/taxfyle/puluminizer/node_modules/google-protobuf/google/protobuf/struct_pb.js:846:13)
        at Function.proto.google.protobuf.Struct.fromJavaScript (/Users/jeff/Projects/taxfyle/puluminizer/node_modules/google-protobuf/google/protobuf/struct_pb.js:912:51)
        at Function.proto.google.protobuf.Value.fromJavaScript (/Users/jeff/Projects/taxfyle/puluminizer/node_modules/google-protobuf/google/protobuf/struct_pb.js:842:55)
        at Function.proto.google.protobuf.Struct.fromJavaScript (/Users/jeff/Projects/taxfyle/puluminizer/node_modules/google-protobuf/google/protobuf/struct_pb.js:912:51)
        at Object.<anonymous> (/Users/jeff/Projects/taxfyle/puluminizer/node_modules/@pulumi/pulumi/runtime/resource.js:409:43)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/jeff/Projects/taxfyle/puluminizer/node_modules/@pulumi/pulumi/runtime/resource.js:17:58)

```

**Comment by mikhailshilkov** [comment]
I tried to reproduce it with recent versions but failed to do so. The `region` property has been removed and the `location` seems to work fine. I'll assume this has been fixed since 2019.
