### ISSUE TITLE
TestNetwork and TestCluster have no recorded baseline 

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-gcp#1577]
### What happened?

When [upgrading providertest library](https://github.com/pulumi/pulumi-gcp/pull/1568) to v0.0.10, the tests on this provider encountered a new panic on TestNetwork/upgrade.

This test does not have a recorded state, whihc it needs to run. A previous providertest version skipped this test; the current version panics instead.

### Example

```
Error:      	Received unexpected error:
            	            	running test preview, update, and edits: initial failure: [/opt/homebrew/bin/pulumi up --non-interactive --yes --skip-preview --event-log /var/folders/87/6b426tw97kl6vb55pl6nbzym0000gn/T/p-it-guineveres-network-d16a3adf-events.json] did not succeed after 1 tries
            	Test:       	TestNetwork/upgrade-preview-only
        upgrade.go:469: Recording preview gRPC logs to /var/folders/87/6b426tw97kl6vb55pl6nbzym0000gn/T/TestNetworkupgrade-preview-only330890701/002/preview-grpc-logs.json
panic: testing: t.Parallel called multiple times [recovered]
	panic: testing: t.Parallel called multiple times

goroutine 314 [running]:
testing.tRunner.func1.2({0x1056b4000, 0x1061e1ec0})
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/testing/testing.go:1545 +0x1c4
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/testing/testing.go:1548 +0x360
panic({0x1056b4000?, 0x1061e1ec0?})
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/panic.go:914 +0x218
testing.(*T).Parallel(0x14001569750?)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/testing/testing.go:1375 +0x2e0
github.com/pulumi/pulumi/pkg/v3/testing/integration.prepareProgram(0x140025e6680, 0x140018e4000)
	/Users/guin/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.103.1/testing/integration/program.go:745 +0x334
github.com/pulumi/pulumi/pkg/v3/testing/integration.ProgramTestManualLifeCycle(0x10620f7f0?, 0x140025e6680?)
	/Users/guin/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.103.1/testing/integration/program.go:847 +0x24
github.com/pulumi/providertest.newProgramTestHelper(_, {{0x1048652c6, 0x15}, {0x0, 0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, ...})
	/Users/guin/go/pkg/mod/github.com/pulumi/providertest@v0.0.10/upgrade.go:550 +0x150
github.com/pulumi/providertest.(*providerUpgradeBuilder).checkProviderUpgradePreviewOnly(0x140015c9eb0, 0x140025e6680)
	/Users/guin/go/pkg/mod/github.com/pulumi/providertest@v0.0.10/upgrade.go:491 +0x400
github.com/pulumi/providertest.(*providerUpgradeBuilder).run(0x140000baeb0, 0x140025e6680, 0x1)
	/Users/guin/go/pkg/mod/github.com/pulumi/providertest@v0.0.10/upgrade.go:303 +0x1b0
github.com/pulumi/providertest.(*ProviderTest).VerifyUpgrade(0x140025a60b0, 0x140025e6680, 0x2d0f52f80012a7a8?)
	/Users/guin/go/pkg/mod/github.com/pulumi/providertest@v0.0.10/upgrade.go:48 +0xe4
github.com/pulumi/providertest.(*ProviderTest).Run.func7(0x140025e6680)
	/Users/guin/go/pkg/mod/github.com/pulumi/providertest@v0.0.10/providertest.go:198 +0x48
testing.tRunner(0x140025e6680, 0x1400262ac60)
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/testing/testing.go:1595 +0xe8
created by testing.(*T).Run in goroutine 339
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/testing/testing.go:1648 +0x33c
exit status 2
FAIL	github.com/pulumi/pulumi-gcp/provider/v7	24.890s
```

### Output of `pulumi about`

n/a

### Additional context

TestNetwork has been skipped in previous runs on `master`: https://github.com/pulumi/pulumi-gcp/actions/runs/7659003249/job/20873447580#step:25:1689

```
TestNetwork/upgrade-preview-only (0s)
      upgrade.go:452: Baseline provider version: 6.67.0
      upgrade.go:456: No pre-recorded state found for 6.67.0. Run in 'snapshot' mode to capture the current state produced by the current provider version.
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Suggest rewriting the tests against providertest 0.10.0 recommended APIs as in here: https://github.com/pulumi/pulumi-gcp/pull/1579 - got network recorded, cluster TBD.

**Comment by t0yv0** [comment]
This is fixed now. Thanks to Venelin for recording cluster.
