### ISSUE TITLE
interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by cosimps** [pulumi/pulumi-gcp#178]
I am receiving the following error when attempting to create a `gcp:storage:BucketACL` object:
```
gcp:storage:BucketACL (bucket-acl):
    error: Plan apply failed: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:52527: connect: connection refused"
```
```
Diagnostics:
  pulumi:pulumi:Stack (test):
    panic: interface conversion: interface {} is nil, not map[string]interface {}
    goroutine 22 [running]:
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceStorageBucketCreate(0xc000424460, 0x2cde9c0, 0xc000290d80, 0xc000424460, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_storage_bucket.go:316 +0x12e1
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0001be280, 0xc0000dcc30, 0xc000872b40, 0x2cde9c0, 0xc000290d80, 0xc000872b01, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:286 +0x3b4
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0001bed80, 0xc000235840, 0xc0000dcc30, 0xc000872b40, 0xc000872b40, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc000274d80, 0x3513540, 0xc0005fb8c0, 0xc000520800, 0xc000274d80, 0x2ccb901, 0xc000520e00)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:611 +0x550
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x3513540, 0xc0005fb8c0, 0x2f6d980, 0xc000520800, 0x3012fe0, 0x4a09458, 0x3513540, 0xc0005fb8c0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1516 +0x86
    github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x3513540, 0xc0005fa750, 0x2f6d980, 0xc000520800, 0xc000493340, 0xc000493360, 0x0, 0x0, 0x34c3be0, 0xc0003e1570)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x30650a0, 0xc000274d80, 0x3513540, 0xc0005fa750, 0xc0000dcbe0, 0xc000492380, 0x3513540, 0xc0005fa750, 0xc000568000, 0x4d4)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1518 +0x158
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b6f00, 0x3525280, 0xc0000b7200, 0xc0004b0600, 0xc0005173b0, 0x49db9d0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:972 +0x470
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0000b6f00, 0x3525280, 0xc0000b7200, 0xc0004b0600, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:1252 +0xda6
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00003af90, 0xc0000b6f00, 0x3525280, 0xc0000b7200, 0xc0004b0600)
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:691 +0x9f
    created by github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:689 +0xa1
```

My code:
```python
acl_resource_opts = pulumi.ResourceOptions(depends_on=[logging_bucket_obj], parent=logging_bucket_obj)
logging_bucket_acl_name = logging_bucket_name + '-acl'
logging_bucket_acl_obj = pulumi_gcp.storage.BucketACL(logging_bucket_acl_name,
                                                      __name__=logging_bucket_acl_name,
                                                      bucket=logging_bucket_obj.name,
                                                      opts=acl_resource_opts,
                                                      predefined_acl=log_bucket_obj_predefined_acl)
pulumi.export(logging_bucket_acl_name, logging_bucket_acl_obj.id)
```

I can create the bucket (`logging_bucket_obj`) just fine but the acl fails.

Currently on version `v0.17.22` but this issue was on `v0.17.21` also.

**Comment by cosimps** [comment]
tagging @stack72 per @lukehoban

**Comment by lukehoban** [comment]
The root of this appears to be the crash due to `panic: interface conversion: interface {} is nil, not map[string]interface {}` @ `resource_storage_bucket.go:316` in the resource provider.

**Comment by lukehoban** [comment]
The failure comes from this line https://github.com/terraform-providers/terraform-provider-google-beta/blob/44b8f519717a43f8fd55ce74176005eca08e71cc/google-beta/resource_storage_bucket.go#L316 in the upstream Terraform Google Beta Provider.

In particular, it appears you are creating a `Bucket` and settings its `website` property to an empty array?  There appears to be a bug in the upstream provider that causes the provider to panic in that case.

**Comment by stack72** [comment]
I believe this fixes the issue https://github.com/terraform-providers/terraform-provider-google-beta/pull/925

We need to wait for this to be merged though

**Comment by cosimps** [comment]
> In particular, it appears you are creating a Bucket and settings its website property to an empty array?

Turns out I was, had a reference to the wrong dictionary value causing an empty array to be passed.

**Comment by lukehoban** [comment]
Closing as this is tracked in https://github.com/terraform-providers/terraform-provider-google-beta/pull/925.

**Comment by barath1997** [comment]
I am having this issue with while i use "google/protobuf/struct.proto" with grpc gateway
I didn't have this issue with grpc v1.31.1 after i upgraded to v1.32.0 i am getting the error : _panic: interface conversion: interface {} is string, not map[string]interface {}_ 
go version : 1.14.4
