### ISSUE TITLE
Creating a GKE cluster causes a SIGSEGV

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-gcp#202]
A fresh `yarn install && yarn link @pulumi/kubernetes && pulumi up` yields the following. It looks like a TF bug, but I didn't have time to investigate whether it was because we passed malformed input into the provider or something.

```
Updating (istio-ci-test):
     Type                 Name                 Status     Info
     pulumi:pulumi:Stack  istio-istio-ci-test             warning: resource plugin gcp is expected to have version >=1.0.1-alpha.15663

     Type                      Name                 Status                  Info
     pulumi:pulumi:Stack       istio-istio-ci-test  **failed**              1 error; 2 warnings; 32 messages
 +   └─ gcp:container:Cluster  test-ci-istio        **creating failed**     1 error; 1 warning

Diagnostics:
  pulumi:pulumi:Stack (istio-istio-ci-test):
    Found incompatible versions of @pulumi/pulumi.  Differing major or minor versions are not supported.
      Version 0.17.28 referenced at node_modules/@pulumi/random/node_modules/@pulumi/pulumi/package.json
      Version 1.0.0-beta.4 referenced at node_modules/@pulumi/gcp/node_modules/@pulumi/pulumi/package.json

    warning: resource plugin gcp is expected to have version >=1.0.1-alpha.1566330047+gf0ee4d1, but has 0.18.7-dev.1559617432+gac5df95.dirty; the wrong version may be on your path, or this may be a bug in the plugin
    warning: resource plugin gcp is expected to have version >=1.0.1-alpha.1566330047+gf0ee4d1, but has 0.18.7-dev.1559617432+gac5df95.dirty; the wrong version may be on your path, or this may be a bug in the plugin
    error: update failed

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x249a0cf]
    goroutine 57 [running]:
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.flattenMaintenancePolicy(...)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:2090
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterRead(0xc0002048c0, 0x2b29580, 0xc0001f2d00, 0x2957260, 0x45edea0)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:935 +0x230f
    github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterCreate(0xc0002048c0, 0x2b29580, 0xc0001f2d00, 0x0, 0x0)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:885 +0x1f6f
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00042e580, 0xc00079a320, 0xc00064df20, 0x2b29580, 0xc0001f2d00, 0xc00064df01, 0x0, 0x0)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:286 +0x3b4
    github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc00017cd80, 0xc00071d868, 0xc00079a320, 0xc00064df20, 0xc00064df20, 0x0, 0x0)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:285 +0x18f
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc0000f2240, 0x32ec440, 0xc000717a10, 0xc0007968c0, 0xc0000f2240, 0x2b18701, 0xc000796b80)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge/provider.go:599 +0x550
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler.func1(0x32ec440, 0xc000717a10, 0x2d8ace0, 0xc0007968c0, 0x2e24fe0, 0x469b200, 0x32ec440, 0xc000717a10)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1331 +0x86
    github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x32ec440, 0xc000716330, 0x2d8ace0, 0xc0007968c0, 0xc000718240, 0xc000718260, 0x0, 0x0, 0x32a1f40, 0xc0001853e0)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:61 +0x360
    github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Create_Handler(0x2e70ae0, 0xc0000f2240, 0x32ec440, 0xc000716330, 0xc00079a280, 0xc000454460, 0x32ec440, 0xc000716330, 0xc000542000, 0x3c9)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/github.com/pulumi/pulumi/sdk/proto/go/provider.pb.go:1333 +0x158
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004f0a80, 0x32fd340, 0xc000582480, 0xc0004ee300, 0xc0005241e0, 0x466ded0, 0x0, 0x0, 0x0)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:971 +0x470
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).handleStream(0xc0004f0a80, 0x32fd340, 0xc000582480, 0xc0004ee300, 0x0)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:1250 +0xd25
    github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000502180, 0xc0004f0a80, 0x32fd340, 0xc000582480, 0xc0004ee300)
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:690 +0x9f
    created by github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
    	/Users/alex/go/src/github.com/pulumi/pulumi-gcp/vendor/google.golang.org/grpc/server.go:688 +0xa1

  gcp:container:Cluster (test-ci-istio):
    warning: urn:pulumi:istio-ci-test::istio::gcp:container/cluster:Cluster::test-ci-istio verification warning: "zone": [DEPRECATED] Use location instead
    error: Plan apply failed: transport is closing

Resources:
    5 unchanged

Duration: 5m14s
```

**Comment by lukehoban** [comment]
This looks like https://github.com/terraform-providers/terraform-provider-google/issues/4010.

**Comment by lukehoban** [comment]
Closing as a dupe.  Also of https://github.com/pulumi/pulumi/issues/2922.  

FWIW - this suggests you were picking up some old version of the provider because you had it on your PATH:

```
warning: resource plugin gcp is expected to have version >=1.0.1-alpha.1566330047+gf0ee4d1, but has 0.18.7-dev.1559617432+gac5df95.dirty; the wrong version may be on your path, or this may be a bug in the plugin
```
