### ISSUE TITLE
Can't get iam policy. Function ignores async process when accessing Output resources.

### ISSUE THREAD

**Issue by krystian-kulgawczuk-pr** [pulumi/pulumi-gcp#403]
It seems that some functions/resources don't respect waiting for asynchronous resources like `Output[T]` and try to access such values immediately.
This seems like a critical bug which needs to be fixed asap.

How to reproduce:

**language**: python 3.6.2
**pulumi version**: 2.8.2
**pulumi sdk version**: 2.8.2
**pulumi-gcp version**: 3.18.0

    from pulumi_gcp import service_account, organizations

    name = "test"
    test_service_account = service_account.Account(
            name,
            account_id=name,
    )
    job_account_member = test_service_account.email.apply(
            lambda email: "serviceAccount:" + email
    )
    test_policy_func_invoker = organizations.get_iam_policy(bindings=[
            {
                "members": [test_account_member],
                "role": "roles/cloudfunctions.invoker",
            },
    ])

**Comment by rsmiley-asi** [comment]
I have a similar issue with aws:
```
from pulumi_aws import iam

    user = iam.User(
        "pulumi_user",
        name="pulumi_user",
        path="/some/path/",
    )

    user_arn = user.arn.apply(lambda arn: arn)

    instance_assume_role_policy = iam.get_policy_document(
        opts=pulumi.ResourceOptions(depends_on=[user]),
        statements=[
            {
                "actions": ["sts:AssumeRole"],
                "effect": "Allow",
                "principals": [{"identifiers": [user_arn], "type": "AWS"}],
            },
        ],
        version="2012-10-17",
    )
```

In this case I've also tried setting `user_arn = user.arn` with no effect. If I explicitly set the expected user ARN with `user_arn = "arn:aws:iam::<account id>:user/some/path/pulumi_user"` then it seems to work, although I'm concerned that there might be an underlying race condition since AWS policies apparently bind to an internal user id on creation that does not get updated. Longer term I'm concerned about the robustness of being able to consume outputs reliably.

There also appears to be an abstraction bleed-through problem in that the error message reported below (in essence "repeated field Values has nil element") bears no resemblance to the problem in Python and therefore gives no guidance to the user on how to resolve it.

```
error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 35, in run_pulumi_func
        func()
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 106, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 282, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 41, in <module>
        main()
      File "./__main__.py", line 37, in main
        create_stack_deployment_iam(this_provider, "production", permission_boundaries)
      File "/asi/aws/infrastructure.py", line 62, in create_stack_deployment_iam
        instance_assume_role_policy = iam.get_policy_document(
      File ".venv/lib/python3.8/site-packages/pulumi_aws/iam/get_policy_document.py", line 317, in get_policy_document
        __ret__ = pulumi.runtime.invoke('aws:iam/getPolicyDocument:getPolicyDocument', __args__, opts=opts).value
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 127, in invoke
        return InvokeResult(_sync_await(asyncio.ensure_future(do_rpc())))
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/sync_await.py", line 95, in _sync_await
        return fut.result()
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 124, in do_rpc
        raise exn
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 108, in do_invoke
        resp = await asyncio.get_event_loop().run_in_executor(None, do_invoke)
      File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File ".venv/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 106, in do_invoke
        raise Exception(details)
    Exception: invocation of aws:iam/getPolicyDocument:getPolicyDocument returned an error: grpc: error while marshaling: proto: repeated field Values has nil element
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```
