### ISSUE TITLE
Pulumi-gcp 4.0.0 fails with cloudrun

### ISSUE THREAD

**Issue by kurkop** [pulumi/pulumi-gcp#468]
Hey, 

I had this error with the new version:

Python code:
```python
class Pulumi:

    def __init__(self):
        self.cfg = Conf('xxx').cfg()

    def running(self):
        cfg = self.cfg
        rs_name = cfg["rs_name"]
        # Output Config
        output("pulumi_name", rs_name)

        # CloudRun
        if cfg["run_enabled"]:
            gcp_run = CloudRun(cfg)
            gcp_run_svc = gcp_run.service()
            gpc_run_iam = gcp_run.iam(gcp_run_svc)
            output("service_run_name", gcp_run_svc.name)
            output("service_run_url", gcp_run_svc.status["url"]) # <- Error
```

```bash
Diagnostics:
  pulumi:pulumi:Stack (liftit-co-sandbox):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "/Users/kurkop/working/liftit/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/kurkop/working/liftit/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 35, in run_pulumi_func
        func()
      File "/Users/kurkop/working/liftit/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 83, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/kurkop/working/liftit/venv/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 106, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 280, in run_path
        run_name, mod_spec, pkg_name).copy()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 233, in <module>
        Pulumi().running()
      File "./__main__.py", line 222, in running
        output("service_run_url", gcp_run_svc.status["url"])
    AttributeError: 'Service' object has no attribute 'status'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

I needed to downgrade to 3.x version to fix it.

**Comment by stack72** [comment]
Hi @kurkop 

The property is now called "Statuses" this is one of the reasons why we had to bump to v4.0.0

Please can you try this and let me know what you think?

Paul

**Comment by kurkop** [comment]
Hey Stack, I tried using `statuses`, it works however the output method was broke. It would be nice to support `status` with a warning until new releases.

**Comment by stack72** [comment]
Hi @kurkop 

This is out of our control as it's a breaking change in the upstream Terraform provider we are using to generate the schema

I'm sorry this causes you a breakage :/

Paul
