### ISSUE TITLE
Panic in resourceComputeInstanceUpdate on instance network interface update

### ISSUE THREAD

**Issue by c2h5oh** [pulumi/pulumi-gcp#490]
Version 4.5.2

Diff:

```  
networkInterfaces: [
              ~ [0]: {
                      ~ network   : "https://www.googleapis.com/compute/v1/projects/[snip]/global/networks/[snip]" => "https://www.googleapis.com/compute/v1/projects/[snip]/global/networks/[snip]"
                      ~ subnetwork: "https://www.googleapis.com/compute/v1/projects/[snip]/regions/us-central1/subnetworks/[snip]" => "https://www.googleapis.com/compute/v1/projects/[snip]/regions/us-central1/subnetworks/[snip]"
                    }
            ]
```

```
panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x1fd0d19]
    goroutine 203 [running]:
    github.com/hashicorp/terraform-provider-google-beta/google-beta.resourceComputeInstanceUpdate(0xc0005e7000, 0x324e720, 0xc000795200, 0x0, 0xffffffffffffffff)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-google-beta@v0.0.0-20201130125119-702fb20d3943/google-beta/resource_compute_instance.go:1259 +0x6db9
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000d9e160, 0x37ccce0, 0xc000044168, 0xc0005e7000, 0x324e720, 0xc000795200, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/resource.go:293 +0x88
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000d9e160, 0x37ccce0, 0xc000044168, 0xc001532070, 0xc00118d380, 0x324e720, 0xc000795200, 0x0, 0x0, 0x0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20200910230100-328eb4ff41df/helper/schema/resource.go:395 +0x390
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfshim/sdk-v2.v2Provider.Apply(0xc000ae2e60, 0x32a2b8a, 0x17, 0x37cdf60, 0xc0012ce030, 0x3807ca0, 0xc00118d380, 0x1, 0x3807ca0, 0xc00118d380, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.15.3/pkg/tfshim/sdk-v2/provider.go:112 +0x1ff
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.(*Provider).Update(0xc00000a1e0, 0x37ccd60, 0xc001264ff0, 0xc001503b00, 0xc00000a1e0, 0x2d84401, 0xc0012a5bc0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.15.3/pkg/tfbridge/provider.go:970 +0x96b
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler.func1(0x37ccd60, 0xc001264ff0, 0x31a8b00, 0xc001503b00, 0x317e560, 0x4fdd6c0, 0x37ccd60, 0xc001264ff0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.15.1-0.20201202214525-260620430c4c/proto/go/provider.pb.go:2305 +0x8b
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x37ccd60, 0xc0012647e0, 0x31a8b00, 0xc001503b00, 0xc001151420, 0xc001151440, 0x0, 0x0, 0x378fd40, 0xc00030aa90)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f6
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Update_Handler(0x320b5a0, 0xc00000a1e0, 0x37ccd60, 0xc0012647e0, 0xc0017a86c0, 0xc000e36600, 0x37ccd60, 0xc0012647e0, 0xc0012a0000, 0xe04)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.15.1-0.20201202214525-260620430c4c/proto/go/provider.pb.go:2307 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00013ca80, 0x3808660, 0xc000602900, 0xc00189a300, 0xc000e80570, 0x4f98258, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:1180 +0x522
    google.golang.org/grpc.(*Server).handleStream(0xc00013ca80, 0x3808660, 0xc000602900, 0xc00189a300, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:1503 +0xd05
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000124110, 0xc00013ca80, 0x3808660, 0xc000602900, 0xc00189a300)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:843 +0xa5
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:841 +0x1fd
```

**Comment by leezen** [comment]
This looks like a bug in the upstream dependency where it should be using the name from the resource data (instead of what's surely a nil instance object): https://github.com/pulumi/terraform-provider-google-beta/blob/upstream-v3.51.0/google-beta/resource_compute_instance.go#L1257

**Comment by mnlumi** [comment]
Closing due to age and inability to repro. Any panic still occurring will be triaged as a high priority item.
