### ISSUE TITLE
google-cloud-sdk error via gke kubectl version error AttributeError: module 'importlib' has no attribute 'util'

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-gcp#493]
GKE kubectl throws the following error:
 `kubectl version`
```Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-14T14:49:35Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: error executing access token command "gcloud config config-helper --format=json": err=exit status 1 output= stderr=Traceback (most recent call last):
  File "/Users/tusharshah/gcp/google-cloud-sdk/lib/gcloud.py", line 104, in <module>
    main()
  File "/Users/tusharshah/gcp/google-cloud-sdk/lib/gcloud.py", line 62, in main
    from googlecloudsdk.core.util import encoding
  File "/Users/tusharshah/gcp/google-cloud-sdk/lib/googlecloudsdk/__init__.py", line 23, in <module>
    from googlecloudsdk.core.util import importing
  File "/Users/tusharshah/gcp/google-cloud-sdk/lib/googlecloudsdk/core/util/importing.py", line 23, in <module>
    import imp
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py", line 23, in <module>
    from importlib import util
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/util.py", line 2, in <module>
    from . import abc
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 26, in <module>
    import re as stdlib_re  # Avoid confusion with the re we export.
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 124, in <module>
    import enum
  File "/Users/tusharshah/gcp/google-cloud-sdk/lib/third_party/enum/__init__.py", line 26, in <module>
    spec = importlib.util.find_spec('enum')
AttributeError: module 'importlib' has no attribute 'util'
```

pulumi version:
`v2.15.6`
language: `typescript`
node: `v14.15.1`
packages:
   gcp: `4.5.2`
   k8s: `2.7.4`

**Steps to reproduce:**

1. Go to the getting started guide for [GKE](https://www.pulumi.com/docs/tutorials/kubernetes/gke/). Steps detailed below.
1. In a new folder gke-hello-world, create an empty project with pulumi new
        `mkdir gke-hello-world`
         `cd gke-hello-world`
         `pulumi new typescript -y`
1. Add the required dependencies:
        `npm install --save @pulumi/pulumi @pulumi/gcp @pulumi/kubernetes`

1. Set the required GCP configuration variables:
       `pulumi config set gcp:project` <YOUR_GCP_PROJECT_HERE>
       `pulumi config set gcp:zone us-central-1a`

1. Open the existing file index.ts, and replace the contents with the following below.
1. 
     ```
          import * as k8s from "@pulumi/kubernetes";
          import * as pulumi from "@pulumi/pulumi";
          import * as gcp from "@pulumi/gcp";
          
          const name = "helloworld";
          
          // Create a GKE cluster
          const engineVersion = gcp.container.getEngineVersions().then(v => v.latestMasterVersion);
          const cluster = new gcp.container.Cluster(name, {
              initialNodeCount: 2,
              minMasterVersion: engineVersion,
              nodeVersion: engineVersion,
              nodeConfig: {
                  machineType: "n1-standard-1",
                  oauthScopes: [
                      "https://www.googleapis.com/auth/compute",
                      "https://www.googleapis.com/auth/devstorage.read_only",
                      "https://www.googleapis.com/auth/logging.write",
                      "https://www.googleapis.com/auth/monitoring"
                  ],
              },
          });
          
          // Export the Cluster name
          export const clusterName = cluster.name;
          
          // Manufacture a GKE-style kubeconfig. Note that this is slightly "different"
          // because of the way GKE requires gcloud to be in the picture for cluster
          // authentication (rather than using the client cert/key directly).
          export const kubeconfig = pulumi.
              all([ cluster.name, cluster.endpoint, cluster.masterAuth ]).
              apply(([ name, endpoint, masterAuth ]) => {
                  const context = `${gcp.config.project}_${gcp.config.zone}_${name}`;
                  return `apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: ${masterAuth.clusterCaCertificate}
              server: https://${endpoint}
            name: ${context}
          contexts:
          - context:
              cluster: ${context}
              user: ${context}
            name: ${context}
          current-context: ${context}
          kind: Config
          preferences: {}
          users:
          - name: ${context}
            user:
              auth-provider:
                config:
                  cmd-args: config config-helper --format=json
                  cmd-path: gcloud
                  expiry-key: '{.credential.token_expiry}'
                  token-key: '{.credential.access_token}'
                name: gcp
          `;
              });
          
          // Create a Kubernetes provider instance that uses our cluster from above.
          const clusterProvider = new k8s.Provider(name, {
              kubeconfig: kubeconfig,
          });
     ```

1. Deploy changes, run pulumi up and select “yes.” Note, provisioning a new GKE cluster takes between 3-5 minutes.
      `pulumi up -y`

1. Create the kubeconfig to run on cli
       `pulumi stack output kubeconfig > kubeconfig`
1. Export the kubeconfig
       `export KUBECONFIG=`pwd`/kubeconfig`
1.  Trigger the error via running kubectl version
     `kubectl version`

**Comment by tusharshahrs** [comment]
Tried this: https://github.com/kubernetes/kubectl/issues/970     with python 3.9
That didn't work.  Last step was:

```
export CLOUDSDK_PYTHON=python2
gcloud components update
export CLOUDSDK_PYTHON=python3
```

Here is the original issue and fix from: https://github.com/kubernetes/kubectl/issues/970
