### ISSUE TITLE
Refreshing state on BucketObject causes InvalidOperationException (C#)

### ISSUE THREAD

**Issue by floyd-may** [pulumi/pulumi-gcp#525]
After refreshing state on a BucketObject, subsequent operations yield an error:

```
System.InvalidOperationException: Expected Pulumi.AssetOrArchive but got System.String deserializing Pulumi.Gcp.Storage.BucketObject.source
       at Pulumi.Serialization.Converter.ConvertObject(String context, Object val, Type targetType)
       at Pulumi.Serialization.Converter.ConvertValue(String context, Value value, Type targetType, ImmutableHashSet`1 resources)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, Boolean remote, Func`2 newDependency, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

## Expected behavior

A refresh doesn't put the stack in an unusable state.

## Current behavior

See above

## Steps to reproduce

1. Create a BucketObject
2. Do `pulumi refresh --yes`
3. Do `pulumi preview`
4. Kaboom

# Additional Information
This seems very similar to what's happening in the Azure provider:
https://github.com/pulumi/pulumi-azure/issues/831

It appears by importing from the checkpoint prior to the `pulumi refresh` I've been able to repair my stack enough to continue forward.

**Comment by pgavlin** [comment]
Thanks for the report!

It sounds like this is a bug in https://github.com/pulumi/pulumi-terraform-bridge. The bridge should be updated s.t. it doesn't lose the fact that these properties are assets/archives, which should fix this problem.
