### ISSUE TITLE
Organizations: GetProject throws AttributeError on 'auto_create_network'

### ISSUE THREAD

**Issue by ns-jreagor** [pulumi/pulumi-gcp#529]
Receiving the following error when attempting to run `pulumi preview`.

```
AttributeError: 'dict' object has no attribute 'auto_create_network'
```

Full stack trace...

```
Diagnostics:
  pulumi:pulumi:Stack (pulumi-budget-alerts-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/Users/testuser/pulumi-budget-alerts/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/testuser/pulumi-budget-alerts/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 34, in run_pulumi_func
        func()
      File "/Users/testuser/pulumi-budget-alerts/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 83, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/testuser/pulumi-budget-alerts/venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 106, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 84, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 285, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 3, in <module>
        from gcp import module_two, module_one
      File "./gcp/__init__.py", line 8, in <module>
        importlib.import_module(f'{__name__}.{pkg}')
      File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "./gcp/netskope_com/__init__.py", line 44, in <module>
        importlib.import_module(f'{__name__}.{pkg}')
      File "/usr/local/Cellar/python@3.9/3.9.2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "./gcp/module_one/configservice.py", line 9, in <module>
        project = organizations.get_project(project_id=project_id, opts=opts)
      File "/Users/testuser/pulumi-budget-alerts/venv/lib/python3.9/site-packages/pulumi_gcp/organizations/get_project.py", line 155, in get_project
        auto_create_network=__ret__.auto_create_network,
    AttributeError: 'dict' object has no attribute 'auto_create_network'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

## Expected behavior

I shouldn't receive this error at all.

## Current behavior

Receiving an error.

## Steps to reproduce

1. Include `gcp.organizations.get_project(project_id=<project_id>, opts=opts)`
2. Try to run `pulumi preview`
3. Receive error.

## Context (Environment)

I need to get project by project ID in order to reference the GCP project number so I can set an alert.

## Affected feature

```
$ venv/bin/pip list
Package    Version
---------- ---------
Arpeggio   1.10.1
attrs      20.3.0
certifi    2020.12.5
chardet    4.0.0
dill       0.3.3
grpcio     1.35.0
idna       2.10
parver     0.3.1
pip        21.0.1
protobuf   3.15.1
pulumi     2.21.2
pulumi-aws 3.30.0
pulumi-gcp 4.12.0
PyYAML     5.4.1
requests   2.25.1
semver     2.13.0
setuptools 53.0.0
six        1.15.0
urllib3    1.26.3
```

```
$ venv/bin/python3 --version
Python 3.9.2
```

**Comment by ns-jreagor** [comment]
It looks like this is from a specific GCP project being manually deleted. I'm not sure why this error is presented because of that but at least I have things working now.

**Comment by lblackstone** [comment]
Sorry for the confusing error message, but glad to hear you got it working. In general, "get" methods won't work if the specified resource doesn't exist.

**Comment by ns-jreagor** [comment]
I don't think that error message is particularly helpful or straight forward, but noted for the future.
