### ISSUE TITLE
crash when running gcp.bigquery.Dataset.get

### ISSUE THREAD

**Issue by confiq** [pulumi/pulumi-gcp#621]
## Steps to reproduce

when I run the following: `gcp.bigquery.Dataset.get('X', id='X')` it works fine! but when I want to get the dataset from another project like this `gcp.bigquery.Dataset.get('X', id='X', project='Y')` I get this error:

```
    panic: interface conversion: interface {} is nil, not string
    goroutine 46 [running]:
    github.com/hashicorp/terraform-provider-google-beta/google-beta.resourceBigQueryDatasetRead(0xc000e87380, 0x40f0540, 0xc000b1d500, 0x60c9890, 0xc000640d80)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-provider-google-beta@v0.0.0-20210713093432-cd048da8bf5b/google-beta/resource_bigquery_dataset.go:489 +0x1bc9
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003583c0, 0x46f7330, 0xc000136030, 0xc000e87380, 0x40f0540, 0xc000b1d500, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20201218231525-9cca98608a5e/helper/schema/resource.go:290 +0x88
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003583c0, 0x46f7330, 0xc000136030, 0xc000f1e770, 0x40f0540, 0xc000b1d500, 0x17, 0xc00124a350, 0x8, 0xc000efd4a0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20201218231525-9cca98608a5e/helper/schema/resource.go:564 +0x1cb
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Refresh(0xc000094640, 0x414b94b, 0x17, 0x46f81a0, 0xc000f17700, 0xc00124a350, 0x8, 0xc000efd380, 0xc0002ffa20)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.2.1/pkg/tfshim/sdk-v2/provider.go:125 +0x1da
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Read(0xc00000a1e0, 0x46f73a0, 0xc000efd3e0, 0xc001139ef0, 0xc00000a1e0, 0x3c15601, 0xc000f1c400)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.2.1/pkg/tfbridge/provider.go:939 +0x692
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler.func1(0x46f73a0, 0xc000efd3e0, 0x3fbbb80, 0xc001139ef0, 0x4010e60, 0x60c8f58, 0x46f73a0, 0xc000efd3e0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.3.2-0.20210526172205-85142462c7ed/proto/go/provider.pb.go:2287 +0x89
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x46f73a0, 0xc000efd110, 0x3fbbb80, 0xc001139ef0, 0xc0011a6900, 0xc0011ff0c8, 0x0, 0x0, 0x46bc220, 0xc0005aaf60)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30a
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Read_Handler(0x40aca20, 0xc00000a1e0, 0x46f73a0, 0xc000efd110, 0xc000ec1380, 0xc0007ca580, 0x46f73a0, 0xc000efd110, 0xc0006ab5e0, 0x9f)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.3.2-0.20210526172205-85142462c7ed/proto/go/provider.pb.go:2289 +0x150
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00072e1c0, 0x47353f8, 0xc000103500, 0xc0012eb560, 0xc000b11f50, 0x60856a0, 0x0, 0x0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
    google.golang.org/grpc.(*Server).handleStream(0xc00072e1c0, 0x47353f8, 0xc000103500, 0xc0012eb560, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
    google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000762070, 0xc00072e1c0, 0x47353f8, 0xc000103500, 0xc0012eb560)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934 +0xab
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd
    	
```

It's worth noting that the GCP project does not have to exist, so basically, anything goes. 

`bigquery.Dataset.get('X', id='X', project='DOES_NOT_EXIST')`

The system that I'm running from:

pip freeze:

```
Arpeggio==1.10.2
attrs==21.2.0
dill==0.3.4
grpcio==1.38.1
parver==0.3.1
protobuf==3.17.3
pulumi==3.7.0
pulumi-gcp==5.12.0
PyYAML==5.4.1
semver==2.13.0
six==1.16.0
```

pulumi version: v3.7.0
Python version: Python 3.9.1

**Comment by tkinz27** [comment]
I have this exact problem today with the latest version of the pulumi gcp classic provider `v6.50.0`.
