### ISSUE TITLE
get_project.py AttributeError: type object 'InvokeOptions' has no attribute 'merge'

### ISSUE THREAD

**Issue by jdoss** [pulumi/pulumi-gcp#915]
### What happened?

Updating to the latest release `v6.39.0` broke get_project. Rolling back to `v6.27.0` fixed it. 

### Steps to reproduce

Upgrade to `v6.39.0` and use `get_project`.

### Expected Behavior

A returned GCP project.

### Actual Behavior

```
Diagnostics:
  pulumi:pulumi:Stack (internal-production):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/jdoss/src/smallstep/nomad/./__main__.py", line 30, in <module>
        instances = create_instances(config_data, network, datacenter, dns_zone, stack)
      File "/home/jdoss/src/smallstep/nomad/./instances.py", line 211, in create_instances
        project = gcp.organizations.get_project()
      File "/home/jdoss/src/smallstep/nomad/venv/lib64/python3.10/site-packages/pulumi_gcp/organizations/get_project.py", line 153, in get_project
        opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    AttributeError: type object 'InvokeOptions' has no attribute 'merge'
```

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.40.2
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.39.0
python  unknown
random  4.4.2

Host     
OS       fedora
Version  37
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jdoss** [comment]
Looks like this broke in v6.34.0.

**Comment by viveklak** [comment]
@jdoss please provide a bit more information about your setup. I tried this with a fresh project and it worked fine. What version of pulumi python package are you using? The merge method most definitely exists in the `InvokeOptions` class has existed since v3.35.0 of the pulumi sdk: https://github.com/pulumi/pulumi/commit/aae9c20ffc4c386994a9cc5208826315d3048542

**Comment by jdoss** [comment]
Hey @viveklak thanks for checking this out. Of course I can't reproduce it anymore. Maybe it was some funkiness between my venv and my local pip env? Sorry for the noise. 

```
$ python --version
Python 3.10.7
$ pulumi version
v3.40.2

$ pulumi about
CLI          
Version      3.40.2
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.39.0
python  unknown
random  4.4.2

Host     
OS       fedora
Version  37
Arch     x86_64

This project is written in python: executable='/home/jdoss/src/smallstep/nomad/venv/bin/python3' version='3.10.7
```
